# 注意 yml 配置文件的编码格式 UTF-8
###########################################################################
server:
  # 端口
  port: 8004
  # 服务
  servlet:
    # 服务名
    context-path: /wyxJavaAdmin
###########################################################################
spring:
  # 数据源
  datasource:
    id: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库url
    url: jdbc:mysql://cdb-jwd16kdk.bj.tencentcdb.com:10069/wyxjava?useSSL=false
    # 数据库用户名
    username: root
    # 数据库用户密码
    password: wyxjava123
###########################################################################
# mybatis 框架
mybatis:
  # 别名包
  type-aliases-package: com.gsm.pojo
  # mapper文件位置
  mapper-locations: classpath:com/gsm/dao/*Mapper.xml
  # 配置
  configuration:
    # 数据库列名 user_name 映射pojo userName 格式转换
    map-underscore-to-camel-case: true
# log日志等级
logging:
  level:
    com.gsm.dao: DEBUG
########################################################################
# 分页插件 pagehelper
pagehelper:
  # 数据库类型
  helper-dialect: mysql
  # 其他一些配置
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
  pageSizeZero: true

